# Model-specific parameters
model_family: "openvla-oft"                    # Model family

use_l1_regression: true                    # If True, uses continuous action head with L1 regression objective
use_diffusion: false                       # If True, uses continuous action head with diffusion modeling objective (DDIM)
num_diffusion_steps_train: 50              # (When `diffusion==True`) Number of diffusion steps used for training
num_diffusion_steps_inference: 50          # (When `diffusion==True`) Number of diffusion steps used for inference
use_film: true                            # If True, uses FiLM to infuse language inputs into visual features
num_images_in_input: 2                     # Number of images in the VLA input (default: 1)
use_proprio: false                          # Whether to include proprio state in input

center_crop: true                          # Center crop? (if trained w/ random crop image aug)
num_open_loop_steps: 8                     # Number of actions to execute open-loop before requerying policy

lora_rank: 32                              # Rank of LoRA weight matrix (MAKE SURE THIS MATCHES TRAINING!)

unnorm_key: ""                             # Action un-normalization key

load_in_8bit: false                        # (For OpenVLA only) Load with 8-bit quantization
load_in_4bit: false                        # (For OpenVLA only) Load with 4-bit quantization

seed: 7                                    # Random Seed (for reproducibility)